
image:
  name: golang:1.12-stretch

# TODO: only do this once and cache the results
before_script:
  - go mod download

stages:
  - build
  - test

build:
  stage: build
  script:
    - make

docker-build:
  stage: build
  script:
    - apt update
    - apt install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common
    - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    - apt update
    - apt install -y docker-ce
    - make docker-build

lint:
  stage: test
  before_script:
    - go mod download
  script:
    - go get -u golang.org/x/lint/golint
    - make lint

test:
  stage: test
  script:
    - make test

