apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "vp-k8s-operator.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    control-plane: {{ template "vp-k8s-operator.name" . }}-controller-manager
    {{ include "vp-k8s-operator.labels" . | nindent 4 }}
  name: {{ template "vp-k8s-operator.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: {{ template "vp-k8s-operator.name" . }}-controller-manager
  template:
    metadata:
      labels:
        control-plane: {{ template "vp-k8s-operator.name" . }}-controller-manager
    {{- if .Values.podAnnotations }}
      annotations:
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
    spec:
      containers:
          {{- if .Values.rbacProxy.enabled }}
        - name: kube-rbac-proxy
          image: {{ .Values.rbacProxy.imageRepository }}:{{ .Values.rbacProxy.imageTag }}
          args:
            - --secure-listen-address=0.0.0.0:{{ .Values.rbacProxy.port }}
            - --upstream=http://{{.Values.metricsHost}}:{{.Values.metricsPort}}/
            - --logtostderr=true
            - --v={{ .Values.rbacProxy.logLevel }}
          ports:
            - containerPort: {{ .Values.rbacProxy.port }}
              name: https
          {{- end }}
        - name: manager
          image: {{ .Values.imageRepository }}:{{ .Values.imageTag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
            - /manager
          args:
            - --metrics-addr={{.Values.metricsHost}}:{{.Values.metricsPort}}
            - --vvp-url={{ .Values.vvpUrl }}
            - --vvp-edition={{ .Values.vvpEdition }}
            {{- if .Values.extraArgs }}
            {{ toYaml .Values.extraArgs | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 443
              name: webhook-server
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            {{- if .Values.certs.enabled }}
            secretName: {{ template "vp-k8s-operator.fullname" . }}-webhook-server-cert
            {{- else }}
            secretName: {{ .Values.certs.existingSecret }}
            {{- end }}
