apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vpnamespaces.ververicaplatform.fintechstudios.com
  creationTimestamp: null
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.4
spec:
  preserveUnknownFields: false
  group: ververicaplatform.fintechstudios.com
  names:
    kind: VpNamespace
    listKind: VpNamespaceList
    plural: vpnamespaces
    singular: vpnamespace
  scope: Namespaced
  versions:
    - name: v1beta1
      additionalPrinterColumns:
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
        - jsonPath: .status.lifecyclePhase
          name: LifecyclePhase
          type: string
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          description: VpNamespace is the Schema for the vpnamespaces API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: VpNamespaceSpec defines the desired state of VpNamespace
              properties:
                roleBindings:
                  items:
                    properties:
                      members:
                        items:
                          type: string
                        type: array
                      role:
                        type: string
                    type: object
                  type: array
              type: object
            status:
              description: VpNamespaceStatus defines the observed state of VpNamespace
              properties:
                lifecyclePhase:
                  description: NamespaceLifecyclePhase is the enum of all possible namespace
                    lifecycle phase Only one of the following states may be specified.
                  enum:
                    - LIFECYCLE_PHASE_INVALID
                    - LIFECYCLE_PHASE_ACTIVE
                    - LIFECYCLE_PHASE_TERMINATING
                    - UNRECOGNIZED
                  type: string
              type: object
          type: object
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
