apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vpnamespaces.ververicaplatform.fintechstudios.com
  creationTimestamp: null
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.metadata.id
    name: Id
    type: string
  - JSONPath: .spec.metadata.resourceVersion
    name: Resource-Version
    type: integer
  - JSONPath: .spec.metadata.createdAt
    name: Created
    type: date
  - JSONPath: .spec.metadata.modifiedAt
    name: Modified
    type: date
  group: ververicaplatform.fintechstudios.com
  names:
    kind: VpNamespace
    plural: vpnamespaces
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: VpNamespace is the Schema for the vpnamespaces API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: VpNamespaceSpec defines the desired state of VpNamespace
          properties:
            metadata:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "make" to regenerate code after modifying this file
                Kind and ApiVersion are mapped automatically Status is mapped to a
                subresource'
              properties:
                createdAt:
                  format: date-time
                  type: string
                id:
                  type: string
                modifiedAt:
                  format: date-time
                  type: string
                name:
                  type: string
                resourceVersion:
                  format: int32
                  type: integer
              type: object
          type: object
        status:
          description: VpNamespaceStatus defines the observed state of VpNamespace
          properties:
            state:
              type: string
          type: object
      type: object
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
